name: Update Stats

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  pull_request_target:  # Use pull_request_target for security
  
  push:
    branches:
      - main
    paths:
      - 'update-pages.yaml'
      
jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permission

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Use v3 for better performance

      - name: Set up Python
        uses: actions/setup-python@v4 # Use v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run Python script
        run: |
          python LoungeStats.py
        continue-on-error: false # Stop if the script fails

      - name: Check if stats.json exists
        run: |
          if [ ! -f "stats.json" ]; then
            echo "stats.json does not exist. Failing workflow."
            exit 1
          fi

      - name: Commit and Push stats.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add stats.json
          if ! git commit -m "Update stats.json"; then
            echo "No changes to commit."
          else
            git push origin main # or your branch name
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Use env for the token
