name: Update Stats 4

on:
  schedule:
    # Runs every 5 minutes, offset by 3 minutes from the first workflow
    - cron: '3-59/5 * * * *'

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run LoungeStats.py
      run: python LoungeStats.py

    - name: Commit and push changes if there are any
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add stats.json
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m 'Update stats'
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
