name: Update MKW Lounge Stats

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run script
        run: python LoungeStats.py

      - name: Commit and Push stats.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add stats.json
          git status # Check which files are staged for commit
          git commit -m "Update stats.json with latest data" || echo "No changes to commit"
          git push https://github.com/${{ github.repository }}:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

          - name: Test Commit
  run: |
    touch testfile.txt
    git add testfile.txt
    git commit -m "Test commit"
    git push https://github.com/${{ github.repository }}:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

