name: Update MKW Lounge Stats

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify repository files
      run: |
        echo "Listing files in the repository:"
        ls -l

    - name: Run Python script
      run: |
        echo "Running LoungeStats.py to create stats.json"
        python LoungeStats.py

    - name: Check if stats.json exists
      run: |
        if [ -f "stats.json" ]; then
          echo "stats.json exists."
        else
          echo "stats.json does not exist."
        fi

    - name: Commit and Push stats.json
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions@github.com"
        git add stats.json
        git status
        git commit -m "Update stats.json" || echo "No changes to commit"
        git push https://github.com/${{ github.repository }}:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git
