name: Update GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you use for GitHub Pages
    paths:
      - 'stats.json'
      - 'update.yaml' # Replace with your actual YAML filename

jobs:
  update-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Commit and push if there are changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Trigger GitHub Pages update"
          git push
